backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\helper\NotifyMessage;
use common\helper\StatusConst;
use common\libs\ClsControllerBackend;
use common\models\ActivityLog;
use common\models\OsrItem;
use common\models\UserAttachment;
use enpii\enpiiCms\libs\NpActiveForm;
use common\models\User;
use common\models\UserSearch;
use common\libs\ClsController;
use frontend\models\ChangePasswordForm;
use yii\helpers\StringHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use enpii\enpiiCms\helpers\ArrayHelper;
use enpii\enpiiCms\helpers\DateTimeHelper;
use enpii\enpiiCms\helpers\CommonHelper;
use yii\filters\AccessControl;
use yii;
use common\models\SystemNotification;
use common\models\OsrUserReviewSearch;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends ClsControllerBackend
{
    public function behaviors()
    {
        $parentOneBehaviors = parent::behaviors();
        $thisOneBehaviors = [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
        return ArrayHelper::merge($parentOneBehaviors, $thisOneBehaviors);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionDashboard()
    {
        return $this->render('dashboard', [

        ]);
    }

    public function actionChunkUpload()
    {
        $scriptUrl = Yii::$app->request->url;
        $modelClassName = Yii::$app->request->getQueryParam('model_class');
        $className = \enpii\enpiiCms\helpers\StringHelper::basename($modelClassName);

        $id = Yii::$app->request->getQueryParam('id');
        $model = $modelClassName::findByID($id);
        if (empty($model)) {
            $model = new $modelClassName();
        }
        $options = [
            'script_url' => $scriptUrl,
            'upload_dir' => $model->getUploadTmpPath() . '/',
            'upload_url' => $model->getUploadTmpUrl() . '/',
            'param_name' => $className,
            'print_response' => false,
            'image_versions' => [
            ],
        ];

        $upload_handler = new BlueImpUploadHandler($options);
        if ($_SERVER['REQUEST_METHOD'] == 'DELETE') {
            return Json::encode([
                'files' => $upload_handler->response,
            ]);
        } else {
            if (!empty($_FILES[$className])) {
                return Json::encode([
                    'files' => $upload_handler->response[$className],
                ]);
            } else {
                $files = $model->getAvatarAttachments();
                return Json::encode([
                    'files' => $files,
                ]);
            }
        }
    }

    public function actionUploadAvatar()
    {
        $imageFile = UploadedFile::getInstanceByName('User[avatar_id]');
        $directory = Yii::getAlias('@root/uploads') . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR;
        if (!is_dir($directory)) {
            mkdir($directory);
        }
        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $uid . '.' . $imageFile->extension;
            $filePath = $directory . $fileName;
            if ($imageFile->saveAs($filePath)) {
                $path = '@webroot/uploads/' . Yii::$app->session->id . DIRECTORY_SEPARATOR . $fileName;
                return Json::encode([
                    'files' => [
                        [
                            'name' => $fileName,
                            'size' => $imageFile->size,
                            "url" => $path,
                            "thumbnailUrl" => $path,
                            "deleteUrl" => 'delete-avatar?name=' . $fileName,
                            "deleteType" => "POST"
                        ]
                    ]
                ]);
            }
        }
        return '';
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        if (empty(Yii::$app->getRequest()->getQueryParam('sort'))) {
            $searchModel->sortDefault = 'created_at';
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,1);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'bulkAction' => false,
            'role' => 'user'
        ]);
    }


    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);

        return $this->render('view', [
            'model' => $user,
        ]);
    }

    /**
     * Create a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new User();
        $model->scenario = User::_SCENARIO_CREATE;
        $model->prepareUserRoles();

        if ($model->load(Yii::$app->request->post())) {
            $model->creator_id = Yii::$app->user->getId();
            $model->is_deleted = 0;
            $model->created_at = DateTimeHelper::toDbFormat();
            $model->updated_at = DateTimeHelper::toDbFormat();

            $model->status = User::_STATUS_PUBLISHED;
            if ($model->status == User::_STATUS_PUBLISHED) {
                $model->published_at = DateTimeHelper::toDbFormat();
            }

            $model->username = strtolower($model->username);
            if(empty($model->username)) {
                $model->username = strtolower($model->email);
            }
            $model->email = strtolower($model->email);

            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return NpActiveForm::validate($model);
            }

            $model->password_salt = uniqid();
            $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash($model->password);

            if ($model->validate([
                        'first_name',
                        'last_name',
                        'mobile_phone',
                        'work_permit_number',
                        'state_ids',
                        'technician_category_ids',
                        'technician_service_type_ids',
                        'email',
                        'password',
                        'password_confirm'
                    ]
                ) && $model->save(false)
            ) {
                Yii::$app->session->addFlash('success', Yii::t(_NP_TEXT_CATE, 'Data created successfully.'));

                // Update UserRoles
                $model->saveUserRoles();
                $this->processAvatarUpload($model);
                /*
                 * insert log after register user
                 */
                // Redirect to View
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->addFlash('error',
                    Yii::t(_NP_TEXT_CATE, 'Data created unsuccessfully. Please recheck the input.'));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $model->prepareUserRoles();

        if ($model->load(Yii::$app->request->post())) {
            $model->updated_at = DateTimeHelper::toDbFormat();

            $model->status = User::_STATUS_PUBLISHED;
            if ($model->status == User::_STATUS_PUBLISHED) {
                $model->published_at = DateTimeHelper::toDbFormat();
            }

            $model->username = strtolower($model->username);
            $model->email = strtolower($model->email);


            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return NpActiveForm::validate($model);
            }

            $model->password_hash = $model->password ? Yii::$app->getSecurity()->generatePasswordHash($model->password) : $model->password_hash;

            if ($model->validate([
                    'first_name',
                    'last_name',
                    'mobile_phone',
                    'work_permit_number',
                    'state_ids',
                    'technician_category_ids',
                    'technician_service_type_ids',
                    'email',
                    'password',
                    'password_confirm'
                ]) && $model->save(false)
            ) {
                $model->saveUserRoles();
                $this->processAvatarUpload($model);
                ActivityLog::insertLogAdminUpdateUser(Yii::$app->user->id, $model->id);
                Yii::$app->session->addFlash('success', Yii::t(_NP_TEXT_CATE, 'Data updated successfully.'));
            } else {
                Yii::$app->session->addFlash('error',
                    Yii::t(_NP_TEXT_CATE, 'Data updated unsuccessfully. Please recheck the input.'));
            }
        }

        $model->password = $model->password_confirm = '';

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $model User
     */
    protected function processAvatarUpload(&$model)
    {
        // Process Avatar
        if (!empty($model->avatar)) {

            // Insert Attachment and update avatar
            foreach ($model->avatar as $key => $filename) {
                if (!empty($filename)) {

backend/views/layouts/_header.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */


use yii\bootstrap\Nav;
use yii\helpers\Url;
use yii\helpers\Html;

?>
<!-- BEGIN HEADER -->
<?php ?>
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="<?= Yii::$app->urlManager->baseUrl; ?>">
                <span class="logo-text">HAT</span>
            </a>

            <div class="menu-toggler sidebar-toggler">
            </div>
        </div>
        <div class="page-header-title">

        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse"
           data-target=".navbar-collapse">

        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<!-- BEGIN HEADER & CONTENT DIVIDER -->
<div class="clearfix"></div>
<!-- END HEADER & CONTENT DIVIDER -->

backend/views/layouts/_sidebar.php
<?php
/**
 * Created by PhpStorm.
 * Author: npbtrac@yahoo.com
 * Date time: 8/7/16 8:52 PM
 */
?>

<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <?php
        echo \enpii\enpiiCms\widgets\Menu::widget([
            'encodeLabels' => false,
            'submenuTemplate' => "\n<ul class=\"sub-menu\">\n{items}\n</ul>\n",
            'linkTemplate' => '<a href="{url}" class="{class}">{label}</a>',
            'labelTemplate' => '<span class="title">{label}</span>',
            'options' => [
                'id' => 'sidebar-primary-menu',
                'class' => 'page-sidebar-menu page-header-fixed side-primary-menu',
                'data-keep-expanded' => 'false',
                'data-auto-scroll' => 'true',
                'data-slide-speed' => 200,
            ],
            'itemOptions' => [
                'class' => 'nav-item',
            ],
            'items' => [
                [
                    'label' => '
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler"> </div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
                ',
                    'labelTemplate' => '{label}',
                    'options' => [
                        'class' => 'sidebar-toggler-wrapper hide',
                    ]
                ],

                // Important: you need to specify url as 'controller/action',
                // not just as 'controller' even if default action is used.
                [
                    'label' => '<i class="fa fa-tachometer"></i>
                    <span class="title">' . Yii::t(_NP_TEXT_CATE, 'Dashboard') . '</span>
                    <span class="arrow"></span>',
                    'url' => Yii::$app->urlManager->createUrl(''),
                    'labelTemplate' => '{label}',
                    'linkClass' => "nav-link nav-toggle",
                    'options' => [
                        'class' => "nav-item start",
                        'style' => 'margin-top: 42px;',
                    ],
                ],
                [
                    'label' => '<i class="icon-user"></i>
                    <span class="title">' . Yii::t(_NP_TEXT_CATE, 'User Management') . '</span>
                    <span class="arrow"></span>',
                    'url' => 'javascript:;',
                    'labelTemplate' => '{label}',
                    'linkClass' => "nav-link nav-toggle",
                    'options' => [
                        'class' => "nav-item start",
                    ],
                    'items' => [
                        [
                            'label' => '<i class="fa fa-list"></i> ' . Yii::t(_NP_TEXT_CATE, 'Standard User Listing'),
                            'url' => ['user/index']
                        ],
                        [
                            'label' => '<i class="fa fa-plus-square-o"></i> ' . Yii::t(_NP_TEXT_CATE, 'Create User'),
                            'url' => ['user/create']
                        ],
                    ]
                ],
                [
                    'label' => '<i class="icon-user"></i>
                    <span class="title">' . Yii::t(_NP_TEXT_CATE, 'Pin Management') . '</span>
                    <span class="arrow"></span>',
                    'url' => 'javascript:;',
                    'labelTemplate' => '{label}',
                    'linkClass' => "nav-link nav-toggle",
                    'options' => [
                        'class' => "nav-item start",
                    ],
                    'items' => [
                        [
                            'label' => '<i class="fa fa-list"></i> ' . Yii::t(_NP_TEXT_CATE, 'Coupon Pin Listing'),
                            'url' => ['coupon-pin/index']
                        ],
                        [
                            'label' => '<i class="fa fa-plus-square-o"></i> ' . Yii::t(_NP_TEXT_CATE, 'Create Coupon Pin'),
                            'url' => ['coupon-pin/create']
                        ],
                    ]
                ],

                ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
            ],
        ]);
        ?>
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->

backend/views/layouts/main-login.php
<?php
/**
 * Created by PhpStorm.
 * Author: npbtrac@yahoo.com
 * Date time: 7/1/16 10:12 PM
 */

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\LoginAsset;
use backend\assets\FontsAsset;
use backend\assets\BootstrapPluginAsset;
use yii\helpers\Html;
use common\widgets\Alert;

$arrJsPosEnd = empty($this->js[\yii\web\View::POS_END]) ? [] : $this->js[\yii\web\View::POS_END];
array_unshift($arrJsPosEnd , "var baseUrl = \"".Yii::$app->urlManager->baseUrl."\";");
$this->js[\yii\web\View::POS_END] = $arrJsPosEnd;

LoginAsset::register($this);
FontsAsset::register($this);
BootstrapPluginAsset::register($this);

$this->beginPage() ?><!DOCTYPE html>
<!--[if IE 8]>
<html lang="<?= Yii::$app->language ?>" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="<?= Yii::$app->language ?>" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="<?= Yii::$app->language ?>">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="" name="description"/>
    <meta content="" name="author"/>

    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->

<body class=" login">
<?php $this->beginBody() ?>
<?= Alert::widget() ?>

<!-- BEGIN LOGO -->
<div class="logo">

    <img src="<?= Yii::$app->urlManager->baseUrl . '/themes/default/images/logo-admin.png'?>" alt="<?= Yii::t('app', 'Admin Panel') ?>" width="320"/>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->

<div class="wrap">
    <div class="container">

        <?= $content ?>
    </div>
</div>
<!-- END LOGIN -->

<!--[if lt IE 9]>

<![endif]-->
<?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

backend/views/layouts/main-media.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use backend\assets\FontsAsset;
use backend\assets\BootstrapPluginAsset;
use yii\helpers\Html;
use common\widgets\Alert;

AppAsset::register($this);
FontsAsset::register($this);
BootstrapPluginAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="white-bg page-header-fixed page-sidebar-closed-hide-logo page-content-white custom-modal">
<?php $this->beginBody() ?>
<div class="page-container">
    <div class="page-content-wrapper">
        <?= $content ?>
    </div>

</div>

<?php $this->beginContent('@app/views/layouts/_footer.php'); ?>
<?= $content ?>
<?php $this->endContent(); ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    
    <?php $this->head() ?>
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
<?php $this->beginBody() ?>

<?php $this->beginContent('@app/views/layouts/_header.php'); ?>
<?= $content ?>
<?php $this->endContent(); ?>

<div class="page-container">
    <?php $this->beginContent('@app/views/layouts/_sidebar.php'); ?>

    <?= $content ?>
    <?php $this->endContent(); ?>
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN THEME PANEL -->
            <div class="theme-panel hidden-xs hidden-sm">
                <div class="toggler"> </div>
                <div class="toggler-close"> </div>
                <div class="theme-options">
                    <div class="theme-option theme-colors clearfix">
                        <span> THEME COLOR </span>
                        <ul>
                            <li class="color-default current tooltips" data-style="default" data-container="body" data-original-title="Default"> </li>
                            <li class="color-darkblue tooltips" data-style="darkblue" data-container="body" data-original-title="Dark Blue"> </li>
                            <li class="color-blue tooltips" data-style="blue" data-container="body" data-original-title="Blue"> </li>
                            <li class="color-grey tooltips" data-style="grey" data-container="body" data-original-title="Grey"> </li>
                            <li class="color-light tooltips" data-style="light" data-container="body" data-original-title="Light"> </li>
                            <li class="color-light2 tooltips" data-style="light2" data-container="body" data-html="true" data-original-title="Light 2"> </li>
                        </ul>
                    </div>
                    <div class="theme-option">
                        <span> Theme Style </span>
                        <select class="layout-style-option form-control input-sm">
                            <option value="square" selected="selected">Square corners</option>
                            <option value="rounded">Rounded corners</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Layout </span>
                        <select class="layout-option form-control input-sm">
                            <option value="fluid" selected="selected">Fluid</option>
                            <option value="boxed">Boxed</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Header </span>
                        <select class="page-header-option form-control input-sm">
                            <option value="fixed" selected="selected">Fixed</option>
                            <option value="default">Default</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Top Menu Dropdown</span>
                        <select class="page-header-top-dropdown-style-option form-control input-sm">
                            <option value="light" selected="selected">Light</option>
                            <option value="dark">Dark</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Sidebar Mode</span>
                        <select class="sidebar-option form-control input-sm">
                            <option value="fixed">Fixed</option>
                            <option value="default" selected="selected">Default</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Sidebar Menu </span>
                        <select class="sidebar-menu-option form-control input-sm">
                            <option value="accordion" selected="selected">Accordion</option>
                            <option value="hover">Hover</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Sidebar Style </span>
                        <select class="sidebar-style-option form-control input-sm">
                            <option value="default" selected="selected">Default</option>
                            <option value="light">Light</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Sidebar Position </span>
                        <select class="sidebar-pos-option form-control input-sm">
                            <option value="left" selected="selected">Left</option>
                            <option value="right">Right</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span> Footer </span>
                        <select class="page-footer-option form-control input-sm">
                            <option value="fixed">Fixed</option>
                            <option value="default" selected="selected">Default</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- END THEME PANEL -->
            <!-- BEGIN PAGE BAR -->
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <a href="index.html">Home</a>
                        <i class="fa fa-circle"></i>
                    </li>
                    <li>
                        <span>Dashboard</span>
                    </li>
                </ul>
                <div class="page-toolbar">
                    <div id="dashboard-report-range" class="pull-right tooltips btn btn-sm" data-container="body" data-placement="bottom" data-original-title="Change dashboard date range">
                        <i class="icon-calendar"></i>&nbsp;
                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                        <i class="fa fa-angle-down"></i>
                    </div>
                </div>
            </div>
            <!-- END PAGE BAR -->
            <!-- BEGIN PAGE TITLE-->
            <h3 class="page-title"> Dashboard
                <small>dashboard & statistics</small>
            </h3>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->

            <?= $content ?>
        </div>
    </div>

</div>

<?php $this->beginContent('@app/views/layouts/_footer.php'); ?>
<?= $content ?>
<?php $this->endContent(); ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/simple.php
<?php
/**
 * Created by PhpStorm.
 * Author: npbtrac@yahoo.com
 * Date time: 8/16/16 5:07 PM
 */
/* @var $this \enpii\enpiiCms\libs\NpView */
/* @var $form \enpii\enpiiCms\libs\NpActiveForm */

use yii\helpers\Html;
use enpii\enpiiCms\libs\NpActiveForm;

\enpii\enpiiCms\webassets\fonts\assets\FontOpenSansAsset::register($this);
\enpii\enpiiCms\webassets\fonts\assets\FontAwesomeAsset::register($this);
\enpii\enpiiCms\webassets\plugins\bootstrapcustom\assets\BootstrapCustomAsset::register($this);
\enpii\enpiiCms\webassets\backend\style1\assets\EnpiiMainAsset::register($this);
\backend\assets\MainAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>

    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <?php $this->head() ?>
</head>
<body class="<?= $this->getBodyClass() ?> relation">
<?php $this->beginBody() ?>

<?= \enpii\enpiiCms\widgets\BootstrapAlert::widget() ?>

<!-- BEGIN HEADER & CONTENT DIVIDER -->
<div class="clearfix"> </div>
<!-- END HEADER & CONTENT DIVIDER -->

<!-- BEGIN CONTAINER -->
<div class="page-container">

    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">

            <?= $content ?>

        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->

</div>
<!-- END CONTAINER -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>