frontend/controllers/PinController.php
<?php
namespace frontend\controllers;

use common\helper\StringHelper;
use common\libs\ClsControllerFrontend;
use common\models\CouponPin;
use yii\web\NotFoundHttpException;
use Yii;
use yii\web\Response;

/**
 * Site controller
 */
class PinController extends ClsControllerFrontend
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionSavePin($id) {
        $id = StringHelper::base64UrlDecode($id);
        $model = $this->findModel($id);
        if($model->is_obtained || !$model) {
            $this->redirect(['site/error']);
        }
        Yii::$app->session->addFlash('image_coupon');
        return $this->render('view-coupon', [
            'model' => $model
        ]);
    }

    protected function findModel($id)
    {
        if (($model = CouponPin::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested item does not exist.'));
        }
    }

    public function actionViewImage($id) {

        $id = StringHelper::base64UrlDecode($id);
        $this->layout = false;
        $model = $this->findModel($id);
        if($model->is_obtained || !$model) {
           $this->redirect(['site/error']);
        }
        $model->prepareCouponPin();
        $model->save();

        $response = Yii::$app->getResponse();
        $response->headers->set('Content-Type', 'image/png');
        $response->format = Response::FORMAT_RAW;
        return $this->renderPartial('image-coupon',[
            'model' => $model
        ]);
    }

}

frontend/views/pin/image-coupon.php
<?php
/**
 * Created by PhpStorm.
 * User: lacphan
 * Date: 11/21/16
 * Time: 5:16 PM
 * @var $model \common\models\CouponPin;
 */
if($model) {
    header('Content-Type: image/png');

    $im = imagecreatefrompng(APP_IMAGE_PATH . '/E-Ticket_Coupon.png');

    $white = imagecolorallocate($im, 255, 255, 255);
    $grey = imagecolorallocate($im, 128, 128, 128);
    $black = imagecolorallocate($im, 0, 0, 0);

    $font = APP_FONT_PATH . '/Korolev-Bold.ttf';

    imagettftext($im, 12, 0, 35, 980, $black, $font, $model->pin);
    imagepng($im);
    imagedestroy($im);
}

frontend/views/pin/view-coupon.php
<?php
/* @var $this \enpii\enpiiCms\libs\NpView
 * @var $model \common\models\CouponPin;
 */
use yii\bootstrap\Html;
use common\helper\StringHelper;

$pageTitle = Yii::t('app', 'Home Page');

$this->setBrowserTitle($pageTitle);
$redirectUrl = Yii::$app->urlManager->createUrl(['site/thank-you']);
?>
    <div class="tmp-home">
        <div class="container">
            <div class="print-btn hide-item">
                <?= Html::button('PRINT / IMPRIMER',[
                    'class' => 'btn btn-default btn-print',
                ])?>
            </div>
            <?php ob_start (); ?>
            <img src="<?= Yii::$app->urlManager->createUrl(['pin/view-image','id' =>  StringHelper::base64UrlEncode($model->id)])?>"
                 alt="">
        </div>
        <?php if($model):?>
            <div id="force-print" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-md" role="document">
                    <div class="modal-wrapper">
                        <div class="modal-content">
                            <div class="print-btn">
                                <?= Html::button('PRINT / IMPRIMER',[
                                    'class' => 'btn btn-default btn-print',
                                ])?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>
<?php

$js = <<<JS
    window.sessionStorage.setItem('is_et',1);
    jQuery(document).ready(function () {
        // jQuery wrapper
        (function ($) {
            $('#main-container').imagesLoaded( function() {
              $('.print-btn').removeClass('hide-item');
              $('.btn-print').click(function() {
                window.print(); 
                document.location.href = '{$redirectUrl}'
              })
            });
            var counter = 15;
    
            setInterval(function() {
                counter--;
                // Display 'counter' wherever you want to display it.
                if (counter === 0) {
                      $('#force-print').modal({
                           backdrop: 'static',
                           keyboard: false
                      });
                }
            
              }, 1000);
        })(jQuery);
    });
JS;
$this->registerJs($js);