common/models/ShortenerItem.php
<?php
namespace common\models;

use common\models\base\MidShortenerItem;

class ShortenerItem extends MidShortenerItem{

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['original_url'], 'string'],
            [['original_url'], 'required'],
            [['original_url'], 'url'],
            [['slug'], 'unique'],
            [['created_at', 'updated_at'], 'safe'],
            [['slug'], 'string', 'max' => 255]
        ];
    }
}

frontend/controllers/ShortenerItemController.php
<?php

namespace frontend\controllers;

use common\models\query\ShortenerItemQuery;
use Yii;
use common\models\ShortenerItem;
use common\models\ShortenerItemSearch;
use common\libs\ClsController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use enpii\enpiiCms\helpers\ArrayHelper;
use enpii\enpiiCms\helpers\DateTimeHelper;
use enpii\enpiiCms\helpers\CommonHelper;

/**
 * ShortenerItemController implements the CRUD actions for ShortenerItem model.
 */
class ShortenerItemController extends ClsController
{
    public function behaviors()
    {
        $parentOneBehaviors = parent::behaviors();
        $thisOneBehaviors = [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
        return ArrayHelper::merge($parentOneBehaviors, $thisOneBehaviors);
    }

    /**
     * Lists all ShortenerItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ShortenerItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRedirect() {
        $slug = !empty($_REQUEST['slug']) ? $_REQUEST['slug'] : '';
        /* @var $model ShortenerItem */
        $model = ShortenerItem::findOne(['slug' => $slug]);
        if (!empty($model->slug)) {
            return $this->redirect($model->original_url);
        } else {
            die('Slug does not exist');
        }

    }

    /**
     * Displays a single ShortenerItem model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Create a new ShortenerItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ShortenerItem();

        if ($model->load(Yii::$app->request->post())) {
            if (empty($model->slug)) {
                $model->slug = uniqid();
            }
            $model->created_at = DateTimeHelper::toDbFormat();
            $model->updated_at = DateTimeHelper::toDbFormat();


            if ($model->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Data created successfully.'));
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Data created unsuccessfully. Please recheck the input.'));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ShortenerItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->updated_at = DateTimeHelper::toDbFormat();

            if ($model->status == ShortenerItem::_STATUS_PUBLISHED) {
                $model->published_at = DateTimeHelper::toDbFormat();
            }

            if ($model->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Data updated successfully.'));
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Data updated unsuccessfully. Please recheck the input.'));
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ShortenerItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if ($this->findModel($id)->putToTrash()) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Data deleted successfully.'));
        } else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Data deleted unsuccessfully.'));
        }

        $queryParams = Yii::$app->request->getQueryParams();
        $indexUrlQueryParams = ArrayHelper::merge([0 => 'index'], $queryParams);

        return $this->redirect($indexUrlQueryParams);
    }

    /**
     * Finds the ShortenerItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ShortenerItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ShortenerItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested item does not exist.'));
        }
    }

    /**
    * Bulk action on selected items
    * @return \yii\web\Response
    */
    public function actionBulk()
    {
        $action = Yii::$app->request->post('bulk-option');
        $selection = (array)Yii::$app->request->post('selection');

        $queryParams = Yii::$app->request->getQueryParams();
        $indexUrlQueryParams = ArrayHelper::merge([0 => 'index'], $queryParams);

        if (count($selection) > 0) {
            $arrIDSuccess = [];
            $arrIDFail = [];

            foreach ($selection as $id) {
                $result = false;
                if ($action == 'delete') {
                    $strAction = Yii::t('app', 'Execute Bulk Deletion.');
                    $result = $this->findModel($id)->putToTrash();
                }
                if ($result) {
                    $arrIDSuccess[] = $id;
                } else {
                    $arrIDFail[] = $id;
                }
            }

            $strAction = empty($strAction) ? '' : $strAction . ' ';

            if (count($arrIDSuccess) > 0) {
                Yii::$app->session->addFlash('success',
                $strAction . Yii::t('app', 'Total {num} item(s) successfully affected: {items}.', [
    'num' => 'count($arrIDSuccess)',
    'items' => 'implode(\', \', $arrIDSuccess)',
]));
            }

            if (count($arrIDFail) > 0) {
                Yii::$app->session->addFlash('error', $strAction . Yii::t('app', 'Total {num} item(s) failed: {items}.', [
    'num' => 'count($arrIDFail)',
    'items' => 'implode(\', \', $arrIDFail)',
]));
            }

        } else {
            Yii::$app->session->addFlash('warning', Yii::t('app', 'No items selected'));
        }

        return $this->redirect($indexUrlQueryParams);
    }
}

frontend/views/shortener-item/_form.php
<?php

use yii\helpers\Html;
use enpii\enpiiCms\libs\NpActiveForm;

/* @var $this enpii\enpiiCms\libs\NpView */
/* @var $model common\models\ShortenerItem */
/* @var $form enpii\enpiiCms\libs\NpActiveForm */
?>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">

            <div class="portlet-title">
                <div class="caption font-green-sharp bold uppercase">
                    <span class="caption-subject bold uppercase"><?= Html::encode($pageTitle) ?></span>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="shortener-item-form">

                    <?php $form = NpActiveForm::begin(['options' => ['class'=> 'single-form', 'role' => 'form']]); ?>

                    <div class="form-body">


                    <?= $form->field($model, 'original_url')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'slug')->textInput(['maxlength' => true]) ?>



                    </div>

                    <div class="form-actions">
                        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>

                    <?php NpActiveForm::end(); ?>

                </div>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

frontend/views/shortener-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ShortenerItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shortener-item-search margin-bottom-10">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="input-group">

        <?= $form->field($model, 'globalSearch', [
            'options' => [
                'tag' => false,
            ],
        ])->textInput([
            'placeholder' => Yii::t(_NP_TEXT_CATE, 'Search...'),
            'class' => 'form-control'
        ])->label(false); ?>

        <span class="input-group-btn">
            <?= Html::submitButton(Yii::t(_NP_TEXT_CATE, 'Search') . ' <i class="m-icon-swapright m-icon-white"></i>', ['class' => 'btn green-haze']) ?>
        </span>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/shortener-item/create.php
<?php

use yii\helpers\Html;


/* @var $this enpii\enpiiCms\libs\NpView */
/* @var $model common\models\ShortenerItem */

$pageTitle = Yii::t('app', 'Create Shortener Item');
$this->setBrowserTitle($pageTitle, 0);

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shortener Item Management'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $pageTitle;

?>
<div class="container shortener-item-create">

    <h3 class="page-title">
        <?=  Html::encode(Yii::t('app', 'Shortener Item Management')) ?>
    </h3>

    <?= $this->render('_form', [
        'model' => $model,
        'pageTitle' => $pageTitle,
    ]) ?>

    <h3>
        <?=  Html::encode(Yii::t('app', 'Latest Action')) ?>
    </h3>
    <?php
    /* @var $models \common\models\ShortenerItem[] */
    $models = \common\models\ShortenerItem::find()->orderBy('created_at DESC')->limit(10)->all();
    foreach ($models as $key => $model) {
        echo '<p class="shortener-item">';
        echo ($key+1). '. ' .Html::a(\yii\helpers\Url::base(true).\yii\helpers\Url::to(['shortener-item/redirect', 'slug' => $model->slug]), ['shortener-item/redirect', 'slug' => $model->slug]);
        echo '</p>';
    }
    ?>

</div>

frontend/views/shortener-item/index.php
<?php
use yii\helpers\Html;
use enpii\enpiiCms\libs\gridview\NpGridView;
use enpii\enpiiCms\libs\NpActiveForm;
use enpii\enpiiCms\helpers\ArrayHelper;

/* @var $this enpii\enpiiCms\libs\NpView */
/* @var $searchModel common\models\ShortenerItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var Yii::$app->request \enpii\enpiiCms\libs\NpRequest */

$pageTitle = Yii::t('app', 'Shortener Item Management');
$this->setBrowserTitle($pageTitle, 0);
$this->params['breadcrumbs'][] = $pageTitle;

$queryParams = Yii::$app->request->getQueryParams();
$bulkQueryParams = ArrayHelper::merge([0 => 'bulk'], $queryParams);
?>
<div class="shortener-item-index">

    <h3 class="page-title">
        <?= Html::encode(Yii::t('app', 'Shortener Item Management')) ?>
    </h3>
    <div class="portlet light bordered">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet">
                    <div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject font-green-sharp bold uppercase">
                                <?= Yii::t('app', 'Shortener Item Listing') ?>
                            </span>

                        </div>
                        <div class="actions">
                            <?= Html::a('<i class="fa fa-plus"></i> <span class="hidden-480">'.
                            Yii::t('app', 'Create Shortener Item'),
                            ['create'],
                            ['class' => 'btn blue btn-outline']) ?>
                        </div>
                    </div>

                    <?= $this->render('_search', ['model'  => $searchModel ])?>
                    <div class="portlet-body">
                    <?php                    // Hidden Form and link action's form must have save ID
                    $formID = 'bulk-actions';
                    $gridID = 'main-list';

                    $this->registerJs(<<<JSCODE
                        jQuery('input[name="selection[]"]').click(function(){
                            if (jQuery('#{$formID}').find('input[name="selection[]"]').length > 0) {
                                jQuery('#{$formID}').find('input[name="selection[]"]').val(jQuery('#main-list').yiiGridView('getSelectedRows'));
                            } else {
                                jQuery('#{$formID}').append($('<input/>').attr({type: 'hidden', name: 'selection[]', value: jQuery('#{$gridID}').yiiGridView('getSelectedRows')}));
                            }
                        });
JSCODE
                    );

                    // Put a hidden form here
                    NpActiveForm::begin(
                        [
                            'options' => [
                                'id' => $formID,
                            ],
                        ]
                    );
                    NpActiveForm::end();

                                        echo NpGridView::widget([
                        'id' => $gridID,
                        'tableOptions' => ['class' => 'kv-grid-table table table-hover table-bordered table-striped table-condensed kv-table-wrap table-common-listing'],
                        'containerOptions'=>['style'=>'overflow: auto;'],
                        'headerRowOptions'=>['class'=>'table-heading'],
                        'filterRowOptions'=>['class'=>'table-filter'],
                        'bordered' => true,
                        'striped' => true,
                        'condensed' => true,
                        'responsive' => true,
                        'hover' => true,
                        'pjax' => false, // pjax is set to always true for this demo
                        // set your toolbar
                        'toolbar' => [
                            [
                                'content' => Html::a('<i class="fa fa-repeat"></i> '. Yii::t('app', 'Reset'), ['index'], [
                                    'data-pjax' => 0,
                                    'class' => 'btn btn-default',
                                    'title' => Yii::t('app', 'Reset all params')])
                                . ' '
                                . Html::a('<i class="fa fa-trash"></i> '. Yii::t('app', 'Delete'), $bulkQueryParams, [
                                     'class' => 'btn btn-danger',
                                     'title' => Yii::t('app', 'Bulk Delete'),
                                     'data' => [
                                         'confirm' => Yii::t('app', 'Are you sure you want to delete?'),
                                         'form' => $formID,
                                         'method' => 'post',
                                         'params' => [
                                             'bulk-option' => 'delete',
                                         ],
                                     ],
                                ])
                            ],
                        ],
                        'panel' => [
                            'heading' => false,
                        ],
                        'resizableColumns' => true,
                        'resizeStorageKey' => 'shortener-item'.Yii::$app->user->id . '-' . date("d"),

                        'persistResize' => true,
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
'columns' => [
                            [
                                'class' => 'enpii\enpiiCms\libs\gridview\NpCheckBoxColumn',
                                'headerOptions' => [
                                    'class' => 'common-column-heading'
                                ],
                                'checkboxOptions' => ['class' => 'default-checkbox'],
                            ],                             [
                                'class' => 'enpii\enpiiCms\libs\gridview\NpSerialColumn',
                                'contentOptions' => ['class' => 'serial-column'],
                                'width' => '1%',
                                'vAlign' => 'middle',
                                'hAlign' => 'right',
                            ], 
                                        'id',
            'slug',
            'original_url:ntext',
            'created_at',
            'updated_at',

                            ['class' => 'enpii\\enpiiCms\\libs\\gridview\\NpActionColumn',
                                'viewOptions' => [
                                    'title' => Yii::t('app', 'View this item'),
                                    'data-original-title' => Yii::t('app', 'View this item'),
                                    'data-container' => 'body',
                                    'class' => 'tooltips',
                                    'data-toggle' => 'tooltip'
                                ],
                                'updateOptions' => [
                                    'title' => Yii::t('app', 'Edit this item'),
                                    'data-original-title' => Yii::t('app', 'Edit this item'),
                                    'data-container' => 'body',
                                    'class' => 'tooltips',
                                    'data-toggle' => 'tooltip'
                                ],
                                'deleteOptions' => [
                                    'title' => Yii::t('app', 'Delete this item'),
                                    'data-original-title' => Yii::t('app', 'Delete this item'),
                                    'data-container' => 'body',
                                    'class' => 'tooltips',
                                    'data-toggle' => 'tooltip'
                                ],
                                'headerOptions' => ['class' => 'np-action-column'],
                            ],
                        ]
                    ]);
                    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/shortener-item/update.php
<?php

use yii\helpers\Html;

/* @var $this enpii\enpiiCms\libs\NpView */
/* @var $model common\models\ShortenerItem */

$pageTitle = Yii::t('app', 'Update {modelClass}', [
    'modelClass' => 'Yii::t(\'app\', \'Shortener Item\')',
]) . ' ID: ' . $model->id;
$this->setBrowserTitle($pageTitle, 0);

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shortener Item Management'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');

?>
<div class="shortener-item-update">

    <h3 class="page-title">
        <?=  Html::encode(Yii::t('app', 'Shortener Item Management')) ?>
    </h3>

    <?= $this->render('_form', [
        'model' => $model,
        'pageTitle' => $pageTitle,
    ]) ?>

</div>

frontend/views/shortener-item/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this enpii\enpiiCms\libs\NpView */
/* @var $model common\models\ShortenerItem */

$pageTitle = Yii::t('app', 'View {modelClass}', [
    'modelClass' => Yii::t('app', 'Shortener Item'),
]) . ' ID: ' . $model->id;
$this->setBrowserTitle($pageTitle, 0);

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shortener Item Management'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'ID: ' . $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');

?>
<div class="container shortener-item-view">

    <h3 class="page-title"><?=  Html::encode(Yii::t('app', 'Shortener Item Management')) ?></h3>

    <div class="caption font-green-sharp bold uppercase">
        <span class="caption-subject bold uppercase"><?= Html::encode($pageTitle) ?></span>
    </div>

    <p>
        <?= Html::a('<i class="fa fa-plus"></i> <span class="hidden-480">'.
            Yii::t('app', 'Create Shortener Item'),
            ['create'],
            ['class' => 'btn blue btn-outline']) ?>
    </p>

    <?= Html::a(Url::base(true).Url::to(['shortener-item/redirect', 'slug' => $model->slug]), ['shortener-item/redirect', 'slug' => $model->slug], ['class' => 'btn btn-primary']) ?>



</div>